### ISSUE TITLE
Doesn't work under Ubuntu 16.10

### ISSUE THREAD

**Issue by sojusnik** [lgpasquale/gnome-shell-extension-disable-screenshield#10]
Hey!

It seems, that your extension isn't working properly under Ubuntu 16.10, because the screen shield still appears after inactivity.

What would be the proper way to debug this?

**Comment by Snowman3456** [comment]
@sojusnik run `gnome-shell --version` and post result.

**Comment by sojusnik** [comment]
```
$ gnome-shell --version
GNOME Shell 3.24.2

```
But [this](https://github.com/lgpasquale/gnome-shell-extension-disable-screenshield/issues/11) one seems to fix it anyway.
