### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [lgpasquale/gnome-shell-extension-disable-screenshield#5]
GNOME 3.18 is out, please update your extension so that people can use it. I have [disabled version checking](http://worldofgnome.org/an-easy-way-to-test-extensions-compatibility-in-gnome-3-12/) and it seems that your extension works well with GNOME 3.18, I haven't spotted any issues yet.

**Comment by kparal** [comment]
Hmm, so it seems it sometimes works and sometimes does not (shield is used). Not sure what causes the difference.

**Comment by kmare** [comment]
yeah, I noticed the same problem as well..

**Comment by lgpasquale** [comment]
I updated the extension to work with gnome 3.18.
I will be closing this issue unless there are any new reports of this happening.

**Comment by kmare** [comment]
Seems to be working fine now, thank you.
